# Use root/example as user/password credentials
version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
  #  command: --default-authentication-plugin=mysql_native_password
    volumes: # 컨테이너 삭제시 생명 주기와 상관 없이 데이터 유지 목적
      - ./db/conf.d:/etc/mysql/conf.d # - [host]:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_song
      - MYSQL_PASSWORD=passsong1234
      - MYSQL_ROOT_PASSWORD=passsong1234
      - TZ=Asia/Seoul